name: CI

 on:
   push:
     branches: [master]
   pull_request:

 jobs:
   test:
     name: Test
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         pair:
           - erlang: 21.2
             elixir: 1.10.3
           - erlang: 23.2
             elixir: 1.11.3
     steps:
       - uses: actions/checkout@v1

       - name: Install OTP and Elixir
         uses: actions/setup-elixir@v1
         with:
           otp-version: ${{matrix.pair.erlang}}
           elixir-version: ${{matrix.pair.elixir}}

       - name: Install dependencies
         run: mix deps.get

       - name: Run tests
         run: mix test --trace

   lint:
     name: lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1

       - name: Install OTP and Elixir
         uses: actions/setup-elixir@v1
         with:
           otp-version: 23.2
           elixir-version: 1.11.3

       - name: Install dependencies
       - run: mix deps.get

       - name: Check dependencies
       - run: mix deps.unlock --check-unused

       - name: Compile
       - run: mix compile --warnings-as-errors
